Seekable source
membraneframework/membrane_file_plugin pull request #40
Opened 2023-06-05 11:55 UTC by varsill

2023-07-18 15:05 UTC, mat-hek requested changes

2023-07-18 15:05 UTC, mat-hek commented on lib/membrane_file/source.ex
> +        end
convert to `cond`

2023-07-20 07:57 UTC, varsill commented on lib/membrane_file/seek_source_event.ex
> +  @type position_t :: offset_t() | {:bof | :cur | :eof, offset_t()} | :bof | :cur | :eof
In fact it's not my invention, it's specified by: https://www.erlang.org/doc/man/file.html#position-2
We also use it here: https://github.com/membraneframework/membrane_file_plugin/blob/7319d702549d6ddb56dd6137dd65a01acf490bfe/lib/membrane_file/seek_event.ex#L18 where and we don't describe it there.
Surely I can add some reference link to the documentation in both these places :D

2023-07-20 08:15 UTC, varsill commented on lib/membrane_file/source.ex
> +  For more information about how to steer reading in `seekable?: true` mode, see: `Membrane.File.SeekSourceEvent`.
done

2023-07-20 08:15 UTC, varsill commented on lib/membrane_file/source.ex
> +    {[event: {:output, %Membrane.File.NewSeekEvent{}}, redemand: :output],
done

2023-07-20 08:17 UTC, varsill commented on lib/membrane_file/source.ex
> +        end
done

2023-08-01 08:56 UTC, mat-hek approved these changes

2023-08-01 08:58 UTC, merged